version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    reviewers:
      - hatsu38
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    reviewers:
      - hatsu38
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    reviewers:
      - hatsu38
    open-pull-requests-limit: 10