name: Assign Auto

on:
  pull_request:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
      - name: Set assignees
        run: gh pr edit $NUMBER --add-assignee $ASSIGNEE
        if: github.actor != 'dependabot[bot]'
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          ASSIGNEE: ${{ github.actor }}